title: Raisonances
description: >-
  Raisonances, la médiation thérapeutique, un soin psychique pour tous
baseurl: ""
url: https://raisonances.care
github:
  url: https://raisonances.care
lang: fr

markdown: kramdown
markdown_ext: "markdown,md"

plugins:
  - jekyll-bootstrap-sass
  - jekyll-assets
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

google:
  fonts:
    - Marcellus+SC
    - Marcellus

bootstrap:
  assets: true

header:
  background: ceramic-3050615_1920.jpg

assets:
  compression: true
  sources:
    - node_modules/jquery/dist
    - node_modules/lodash
    - _site/assets/javascripts/bootstrap

include:
  - _pages

exclude:
  - Makefile
  - node_modules/
  - vendor/
  - .bundle/
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
