title: Raisonances
subtitle: Le soin psychique par la médiation
description: >-
  Raisonances, le soin psychique par la médiation
baseurl: ""
url: https://raisonances.care
github:
  url: https://raisonances.care
lang: fr
header:
  background: site-header.jpg

markdown: kramdown
plugins:
  - jekyll-assets
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

google:
  fonts:
    - Playfair+Display+SC
    - Playfair+Display

stylesheets:
  - https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css

assets:
  compression: true

include:
  - _pages
