title: Your awesome title
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: https://raisonances.github.io
github:
  url: https://raisonances.github.io
lang: fr

markdown: kramdown
plugins:
  - jekyll-assets
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

google:
  fonts:
    - Lora

stylesheets:
  - https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css

assets:
  compression: true
