title: Raisonances
description: >-
  Raisonances, la médiation thérapeutique, un soin psychique pour tous
baseurl: ""
url: https://raisonances.care
github:
  url: https://raisonances.care
lang: fr

markdown: kramdown
markdown_ext: "markdown,md"

plugins:
  - jekyll-assets
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

google:
  fonts:
    - Playfair+Display+SC
    - Playfair+Display

stylesheets:
  - https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css

assets:
  compression: true
sass:
  sass_dir: _sass
  style: compressed

include:
  - _pages

header:
  background: site-header.jpg
